### ISSUE TITLE
Facer crashing on edit of any Text Layer and Watch Face

### ISSUE THREAD

**Issue by renderinfo** [fodawim/Facer-Support#111]
I sent several Crash Reports via Facer when it crashed.  Uninstalled/Reinstalled - Cleared data and cache.  Not sure if this has anything to do with the Beta (I am using 1.6 Beta 4-(174)), but it's been happening for a while, so I am dropping a bug/issue.
LG Urbane 
Android Wear 1.1.1.1864693
Google Play Services 7.3.34
Android OS 5.1.1
Build number LJZ13E

Phone Nexus 6
Android Wear 1.1.1.1889093
Android Version 5.1
Kernel version 3.10.40-geec2459
Build number LMY47M
Facer Build Information 1.6 Beta 4-(174)

Again, I am able to edit shape and image layers.  I am able to reorder any and all layers.  But when I touch any text layer on any watch face to edit/open, Facer crashes and I've sent crash reports.

Thanks!

**Comment by fodawim** [comment]
Hey!

Can you confirm this is still happening as of 1.6 Beta 6?

**Comment by renderinfo** [comment]
Wow, thank you so much for getting back to me personally.

Yes, it has been happening on 1.6 Beta 6 for "both" of the builds I have gotten recently
1.6 Beta 6-(174)
1.6 Beta 6-(179)  <- This is what I have now.

Here's my other relevant info:
LG Urbane 

Android Wear 1.1.1.1864693

Google Play Services 7.3.34

Android OS 5.1.1

Build number LJZ13E


Phone Nexus 6

Android Wear 1.1.1.1889093

Android Version 5.1

Kernel version 3.10.40-geec2459

Build number LMY47M

The only other "item of significance" is that I recently changed out/"unpaired" my Moto 360 once I received my LG Urbane.  I have not been able to edit any text layers since I've had the Urbane.  I have never directly modified my sdcard/Facer directory, but it still retained all the watch faces I've been collecting since I've had the Moto 360.  But I have uninstalled/reinstalled Facer, including Clear Data/Clear Cache and that has not seemed to help.

I initially suspected some kind of permissions/file access issue, but since Facer is letting me edit Shape and Image layers, I don't think that's the issue.  

I LOVE THE NEW FEATURE where I hit the "settings icon" on my watch and swap through my most recently used Facer watch faces using only my watch.  So, everything appears working on Facer (including weather and steps) except my ability to edit any text layer on any watch face.

I am more than willing to send you anything or try anything.

Thanks so much for your support,
Robert Grindell





Date: Fri, 15 May 2015 10:14:39 -0700

**Comment by fodawim** [comment]
Think I may have figured this one out. :)

I'll try to get a build out tonight.

**Comment by renderinfo** [comment]
Build 181 fixed it, thank you very much. I wonder what it was...

Thanks,
Renderinfo
Robert

--- Original Message ---

**Comment by fodawim** [comment]
Was just a null pointer in a rare case. Thanks for your help and detailed info :)
