### ISSUE TITLE
Add trigonometry to math

### ISSUE THREAD

**Issue by Wikiwix** [fodawim/Facer-Support#95]
I want to use a circle that marks the minutes/seconds handle. Therefore (to avoid creating a picture, I wanted to use this: 50*sin(#DWFMS#)+120 and that 50*cos(#DWFMS#)+120
for the x and y coordinate (should move in a circle with radius 50 around the Point (120,120))
But it seems like trigonometry is not supported...
Hopefully I am only missing something...

If as a new feature: the input should be in degree to make easy use of the rotation tags

**Comment by fodawim** [comment]
This is already in the app.

Math needs to be wrapped by parentheses, including trig functions.

`(50*sin(#DWFMS#)+120)` and `(50*cos(#DWFMS#)+120)` should work.

**Comment by Wikiwix** [comment]
Thanks and good to know:
Perhaps there should be a hint about the wrapping by parentheses (I had this problem before, but did find the solution without actually knowing the cause)
